### ISSUE TITLE
Only single step two player mode, no real two player mode!?

### ISSUE THREAD

**Issue by Counterfeiter** [werner-duvaud/muzero-general#141]
Hello,

first of all: I thought the console menu would be really annoying, but I really like this style to start training and add my own game env that easy as well.

I wrote a game engine for the board game Kingdom Builder (https://github.com/Counterfeiter/KingdomBuilder) and build a wrapper (work still ongoing). The problem is, the two player option will fail, because each step the player should alternate, but that's not the always the case for some games.

So, please correct me if I am wrong: I can select one player game and muzero tries to maximizes the score for both player. So this combined players collaborate a kind of?! 

My game environment provides a player index, also that's the next step in your TODO list to make it multiplayer. I think the multiplayer option and the "more then on step per player" option is really close to implement. Maybe we could talk here about req. implementation changes and later I could do a pull request.

Thanks and best regards

Sebastian

**Comment by JohnPPP** [comment]
Hi Sebastian,

Very good question, which I'm not sure my answer is correct. Keep that in mind ;)

I think that by setting up a single-player game, MuZero will try to maximize the combined score of both of them, and not each other. I think the players will collaborate towards a maximum score (the sum of the scores)

Since this implementation can play Tic-Tac-Toe (2 player game) I think a two-player game will work out well.

I'm also looking eagerly to the multi-player implementation, especially if they can have different policy networks associated with different rewards.

Perhaps someone more knowledgeable than me can share their perspective.

Thank you,
João

**Comment by ahainaut** [comment]
Hi Counterfeiter,
An other solution for your environment would be to add a « pass » action so you can artificially turn your game into a turn by turn game.
