### ISSUE TITLE
Reward computation based on next state instead of (state, action)

### ISSUE THREAD

**Issue by FXDevailly** [werner-duvaud/muzero-general#153]
In the code (in the dynamics function/method), I believe that r_k is computed based on s_k (next_encoded_state) instead of (s_k-1,a_k).

Here is the pseudo function from the MuZero paper:
![paper](https://user-images.githubusercontent.com/35671640/115893838-a4786c00-a426-11eb-8865-25d96420dfdb.PNG)

Here is the illustration from the MuZero paper:
![MuZero illustration](https://user-images.githubusercontent.com/35671640/115893837-a4786c00-a426-11eb-9594-1bd9c5cc1edd.PNG)

The code computes r_1 using s_1 instead of (s_0,a_1)

Here is the corresponding part of models.py : 

If I'm correct, 'x' (i.e., s_k-1, a_k)should be the input to the  'dynamics reward network':

![Code](https://user-images.githubusercontent.com/35671640/115893833-a4786c00-a426-11eb-9569-6ed952710423.PNG)

Of course in practice, s_k is just a transformation of (s_k-1, a_k), so it's not likely to cause any issue. Is it done on purpose ?

**Comment by werner-duvaud** [comment]
Hi,
Yes you're right, it's a very interesting discussion. We had this kind of discussion during the implementation.

This [diagram](https://github.com/werner-duvaud/muzero-general/blob/master/docs/muzero-network-werner-duvaud.png) sums up what you are saying. We preferred to put the reward prediction network after the resnet so that the calculation of the effect of the action on the reward is shared between the resnet and the reward network. The reward network just has to estimate a state instead of also having to calculate the effect of the action. Either way, both ways of doing it should work.
It would be a good experiment.

**Comment by FXDevailly** [comment]
> Hi,
> Yes you're right, it's a very interesting discussion. We had this kind of discussion during the implementation.
> 
> This [diagram](https://github.com/werner-duvaud/muzero-general/blob/master/docs/muzero-network-werner-duvaud.png) sums up what you are saying. We preferred to put the reward prediction network after the resnet so that the calculation of the effect of the action on the reward is shared between the resnet and the reward network. The reward network just has to estimate a state instead of also having to calculate the effect of the action. Either way, both ways of doing it should work.
> It would be a good experiment.

Interesting indeed and it makes sense ! Thanks for the quick reply. 
Both seem to work fine on my end (cannot conclude regarding performance so far however).

**Comment by ahainaut** [comment]
Closing this issue since we are not likely to change the formula of the current implementation but feel free to re open the issue for any thoughts / results of experimentations you could have on this subject !
