### ISSUE TITLE
ray not support windows，so muzero-general can not run on windows

### ISSUE THREAD

**Issue by zfavourite99** [werner-duvaud/muzero-general#4]
please support windows，thanks.

**Comment by werner-duvaud** [comment]
Hello,
This is not planned at the moment.
Ray could become compatible with windows (see https://github.com/ray-project/ray/issues/631).

You can also use a virtual machine or the Windows Subsystem for Linux to run it.

**Comment by ihexx** [comment]
@zfavourite99 Hey there, I ran into the same thing today so I threw together a [quick port using torch multiprocessing instead of ray.](https://github.com/ihexx/muzero-general)
There's a few differences in how I handle the asynchronous communications so I don't reproduce exactly the same results, but the performance is on par with the original version.

The ray API is cleaner though, so I don't think its worth making a pull request for

**Comment by werner-duvaud** [comment]
@ihexx Thank you
I will put the link in the readme.

**Comment by zfavourite99** [comment]
@ihexx Thank you.  这帮了我很大的忙.
