### ISSUE TITLE
Default Q value for unexplored nodes

### ISSUE THREAD

**Issue by fidel-schaposnik** [werner-duvaud/muzero-general#52]
Here

https://github.com/werner-duvaud/muzero-general/blob/18cad41cacd8c113303e6ffcc460e69bf4a68a7b/self_play.py#L370

you assign value 0 to nodes that haven't yet been visited. However, since values are normalized to the range [0,1] a better estimate to assign to unexplored nodes would be 0.5. Otherwise it seems that the exploration-exploitation trade-off will lean towards exploitation (after the first arbitrary choice, that branch will likely have the maximum value in min_max_stats, and therefore have value 1, particularly when values and rewards are positive).

**Comment by nemtiax** [comment]
In AlphaZero, they initialize unexplored nodes to value=0 where 0 corresponds to a loss.  See:

http://talkchess.com/forum3/viewtopic.php?f=2&t=69175&start=70#p781765

The argument is that most moves in chess, at least, are terrible and so you should assume they're losing until proven otherwise:

"Yes and 0 seems to work best. Assumption being that most positions have 1 or at most a few good moves. All other moves are akin to passing or worse. In most equal-ish positions, passing will give the opponent a big advantage."

While it's true that this strategy discourages exploration, that may be a desirable feature, at least for some games.

**Comment by fidel-schaposnik** [comment]
I see, thanks for the clarification! However, one should probably be more careful with MuZero: even if most moves are "bad" like in chess, MuZero doesn't really know that until after some training (reward and value heads produce garbage initially), so it can get stuck into exploring only some branches of the game tree, and then after the policy head is trained on a skewed set of initial games those branches may never get to be explored.

In any case, I guess this could become a game-specific hyperparameter, especially relevant for games with small action spaces...

**Comment by nemtiax** [comment]
Yeah, I agree.  Just because that was a useful heuristic for chess doesn't mean it's universally true.  It definitely strikes me as something worth exploring more, at least.

**Comment by ahainaut** [comment]
Hi, 

This is a sensitive subject as it has not been developped in the original paper and the choice of adding a new hyperparameter to control node initialization could be interesting to test. 
Concerning our implementation, we decided to follow the [pseudocode](https://arxiv.org/src/1911.08265v2/anc/pseudocode.py) by initializing value to 0 regardless of the game. As this was used by DeepMind for both board games and Atari, this initialization could be appropriate for all kind of environments. 

Running some tests would be great to clear the matter.

**Comment by fidel-schaposnik** [comment]
My experiments (not using this implementation though) show that at least CartPole and TicTacToe can benefit a lot from this change, especially when using max of pairs (ucb_score, action) in select_child as in the original pseudocode (this results in always choosing the last action in case of draws, and has been corrected here in https://github.com/werner-duvaud/muzero-general/blob/98cb784a06a8c25fe4a99a3c71d5358b357c5ef0/self_play.py#L341 )

**Comment by werner-duvaud** [comment]
This is an interesting question to explore. 
On the few tests that I did, the impact of this hyperparameter was not very clear, especially since there are already hyperparameters to increase exploration. For the moment I think that there are already too many hyperparameters and that adding a hyperparameter for that will not help much. I prefer to wait until the importance of this value is clearly demonstrated.
Please, keep me posted if you still notice strong improvements thanks to this hyperparameter!
