### ISSUE TITLE
Better Reward assignment at the end of Games

### ISSUE THREAD

**Issue by TimZF** [werner-duvaud/muzero-general#56]
If for example you want to implement a chess game and give a reward of 1 to the winner and -1 to the looser at the end of the Game.

In the current implementation this wouldn't really work, cause you only know that a game is finished when somebody wins and then its not possible to give the looser his reward (in hindsight), unless you would iterate over all players with a dummy observation and then give them their rewards. So without this only the last person to play gets a reward. 

I would propose to change the AbstractGame wrapper to include a get_reward method which returns a reward for each player and then assigns the last time that player acted that reward. This would only happen at the end of the game and shouldn't effect gym like games which give a reward for each step, i think.

But i'm not sure about this so i thought i make an issue to get feedback before actually changing it and making a pull request.

**Comment by werner-duvaud** [comment]
Hi,

Thanks for your interest in the project.

I think the question is why do you want to do this?

About a way to do it, as you said, you can just do not return Done directly after winning but give a dummy observation with a negative reward for the loser.

But in the MCTS a reward of 1 for a player is perceived as -1 for the opponent (neglecting the discount), therefore I am not sure about the utility of insisting on the defeat of the other since  it's already taken into account.

**Comment by TimZF** [comment]
Yeah thats right
