### ISSUE TITLE
Is it possible to get the best action sequence?

### ISSUE THREAD

**Issue by autonomobil** [werner-duvaud/muzero-general#7]
Is it possible to extract not only the best immediate action, but the best action sequence over the planning horizon? 

So a vector of actions with length  `self.config.num_simulations`

**Comment by werner-duvaud** [comment]
The best action is relative but yes we can.
With a trained network, you can successively apply `recurrent_inference` by choosing the best action as many times as you want to have the best succession of actions according to the neural network.

We can also retrieve the policy and the visit count of each node in the MCTS, but the actions will not necessarily be successive because of the exploration.

Be careful though, you can never be sure that these actions are possible actions in reality.
