### ISSUE TITLE
Can this repo reproduces MuZero paper's score?

### ISSUE THREAD

**Issue by Liu-SD** [werner-duvaud/muzero-general#74]

**Comment by werner-duvaud** [comment]
Hi,

We are going to need a few more TPUs to answer your question ;)

**Comment by Liu-SD** [comment]
Haha, what about the learning curves of games you listed? Or other statistics such as convergence time, final scores?

**Comment by werner-duvaud** [comment]
Most of the games listed in this repo are not in the paper so I cannot compare. In addition, some hyperparameters can be optimized. But on most games the level of MuZero is improving continuously.  We got a good MuZero on cartpole, lunarlander, tic tac toe, connect4 and some Grid World environments + MuJoCo Inverted pendulum and Inverted Double Pendulum.
I noticed that with the right hyperparameters MuZero is very sample efficient but it is more computationaly intensive and long to train because we have to learn a model and do a mcts at each step.

**Comment by hustqj** [comment]
I am tring to run muzero in atari game, but it can't convergence. do you test in atari game?

**Comment by werner-duvaud** [comment]
Hi,

[atari.py](https://github.com/werner-duvaud/muzero-general/blob/master/games/atari.py) uses the hyperparameters proposed in the paper and we have not tested it.
But we are currently trying to solve Breakout with a simpler configuration.
