### ISSUE TITLE
Unpickling error when running some training and attempting to reload model

### ISSUE THREAD

**Issue by LukeWood** [werner-duvaud/muzero-general#76]
Using checkpoint from results/cartpole/2020-08-31--17-00-26/model.checkpoint
Traceback (most recent call last):
  File "muzero.py", line 581, in <module>
    muzero.load_model(
  File "muzero.py", line 402, in load_model
    self.replay_buffer = pickle.load(open(replay_buffer_path, "rb"))
_pickle.UnpicklingError: A load persistent id instruction was encountered,
but no persistent_load function was specified.

**Comment by werner-duvaud** [comment]
Hi,

I can't reproduce it.

This can happen if you enter the model.checkpoint for the replay buffer path (instead of the path for replay_buffer.pkl).

model.checkpoint contains the weights and training information but the replay buffer is stored as replay_buffer.pkl

Can you make sure that you are loading replay_buffer.pkl for the replay buffer path ?

**Comment by LukeWood** [comment]
Ah that makes sense - didn't realize that!  That explains it
